/**
 * routes/adminRoutes.js  — SECURITY UPDATE
 *
 * CHANGES FROM PREVIOUS VERSION:
 *   ✅ Registration now requires a one-time invite token (no env var exposed to frontend)
 *   ✅ Login route has a dedicated strict rate limiter (5 attempts / 15 min per IP)
 *   ✅ New POST /invite  — super_admin generates a single-use invite link
 *   ✅ New GET  /admins/pending — super_admin sees accounts waiting for approval
 *   ✅ Password policy: min 12 chars, 1 uppercase, 1 number
 *   ✅ Pre-hashes password explicitly so Admin model hook never double-hashes
 *   ✅ All other existing routes unchanged (quizzes, bundles, upload, etc.)
 *
 * ZERO IMPACT on parent/child routes — this file only touches /api/admin/*
 */

const { setAuthCookie }    = require("../utils/setCookies");
const ADMIN_COOKIE_MAX_AGE = 2 * 60 * 60 * 1000; // 2 hours

const express    = require("express");
const path       = require("path");
const fs         = require("fs");
const jwt        = require("jsonwebtoken");
const bcrypt     = require("bcrypt");
const { v4: uuidv4 } = require("uuid");
const multer     = require("multer");
const rateLimit  = require("express-rate-limit");

const { requireAdmin }  = require("../middleware/adminAuth");
const Admin             = require("../models/admin");
const AdminInvite       = require("../models/adminInvite");   // ✅ NEW
const Quiz              = require("../models/quiz");
const Question          = require("../models/question");
const QuizCatalog       = require("../models/quizCatalog");
const Child             = require("../models/child");
const Purchase          = require("../models/purchase");
const connectDB         = require("../config/db");

const router     = express.Router();
const JWT_SECRET = process.env.JWT_SECRET || process.env.PARENT_JWT_SECRET;

// ═══════════════════════════════════════════════════════════
// ✅ STRICT rate limiter for the login endpoint only
//    5 attempts per 15 minutes per IP — persists in memory
//    (upgrade to Redis store for multi-instance deployments)
// ═══════════════════════════════════════════════════════════
const adminLoginLimiter = rateLimit({
  windowMs:        15 * 60 * 1000,
  max:             5,
  message:         { error: "Too many login attempts. Try again in 15 minutes." },
  standardHeaders: true,
  legacyHeaders:   false,
  // keyGenerator defaults to req.ip — correct behaviour
});

// ─── helpers ───────────────────────────────────────────────

function requireSuperAdmin(req, res, next) {
  if (req.admin?.role !== "super_admin") {
    return res.status(403).json({ error: "Super admin access required" });
  }
  next();
}

// ═══════════════════════════════════════════════════════════
// PUBLIC: Seed / first-run check
// Called by the frontend on /kai-ops-9281 to know whether
// the DB has any admin accounts at all yet.
// ═══════════════════════════════════════════════════════════
router.get("/check", async (req, res) => {
  try {
    await connectDB();
    const count = await Admin.countDocuments();
    return res.json({ has_admin: count > 0 });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// ═══════════════════════════════════════════════════════════
// PUBLIC: Admin Register — requires a valid invite token
//
// The invite token is a 64-char hex string generated by
// POST /api/admin/invite (super_admin only). It is stored
// in MongoDB, not in any env var or frontend bundle.
//
// Flow:
//   1. super_admin calls POST /api/admin/invite
//   2. Backend creates AdminInvite record, returns invite URL
//   3. super_admin sends URL to colleague (Slack / email)
//   4. Colleague opens URL → AdminRegister.jsx reads ?invite= from URL
//   5. Colleague submits form → this endpoint validates the token
//   6. Account created as admin + pending — super_admin approves
// ═══════════════════════════════════════════════════════════
router.post("/register", async (req, res) => {
  try {
    await connectDB();

    const invite_token = String(req.body?.invite_token || "").trim();
    const name         = String(req.body?.name         || "").trim();
    const email        = String(req.body?.email        || "").trim().toLowerCase();
    const password     = String(req.body?.password     || "");

    // ── Validate invite token ──────────────────────────────
    if (!invite_token) {
      return res.status(403).json({
        error: "A valid invite link is required to register. Ask a super admin for an invite.",
      });
    }

    const invite = await AdminInvite.findOne({
      token:    invite_token,
      used:     false,
      expiresAt: { $gt: new Date() },
    });

    if (!invite) {
      return res.status(403).json({
        error: "This invite link is invalid or has expired. Ask a super admin for a new one.",
      });
    }

    // ── Validate inputs ────────────────────────────────────
    if (!name)  return res.status(400).json({ error: "Name is required" });
    if (!email) return res.status(400).json({ error: "Email is required" });

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return res.status(400).json({ error: "Valid email is required" });
    }
    if (!password || password.length < 12) {
      return res.status(400).json({ error: "Password must be at least 12 characters" });
    }
    if (!/[A-Z]/.test(password)) {
      return res.status(400).json({ error: "Password must contain at least one uppercase letter" });
    }
    if (!/[0-9]/.test(password)) {
      return res.status(400).json({ error: "Password must contain at least one number" });
    }

    const existing = await Admin.findOne({ email });
    if (existing) {
      return res.status(409).json({ error: "An account with this email already exists" });
    }

    // ── Mark invite as used BEFORE creating admin ──────────
    // (prevents race condition where same link used twice simultaneously)
    invite.used = true;
    await invite.save();

    // ── Hash password explicitly ───────────────────────────
    const password_hash = await bcrypt.hash(password, 12);

    const admin = await Admin.create({
      email,
      name,
      password_hash,
      role:   "admin",     // never super_admin via UI
      status: "pending",   // super_admin must approve
    });

    return res.status(201).json({
      ok:      true,
      pending: true,
      message: "Account created. A super admin must approve it before you can log in.",
      admin:   { name: admin.name, email: admin.email, role: admin.role, status: admin.status },
    });
  } catch (err) {
    console.error("Admin register error:", err);
    return res.status(500).json({ error: "Registration failed" });
  }
});

// ═══════════════════════════════════════════════════════════
// PUBLIC: Admin Login
// ✅ Protected by dedicated rate limiter (5 / 15 min)
// ═══════════════════════════════════════════════════════════
router.post("/login", adminLoginLimiter, async (req, res) => {
  try {
    await connectDB();

    const email    = String(req.body?.email    || "").trim().toLowerCase();
    const password = String(req.body?.password || "");

    if (!email || !password) {
      return res.status(400).json({ error: "Email and password are required" });
    }

    const admin = await Admin.findOne({ email });
    if (!admin) {
      return res.status(401).json({ error: "Invalid email or password" });
    }

    const isValid = await admin.comparePassword(password);
    if (!isValid) {
      return res.status(401).json({ error: "Invalid email or password" });
    }

    if (admin.status === "pending") {
      return res.status(403).json({
        error:  "Your account is pending approval from a super admin.",
        status: "pending",
      });
    }
    if (admin.status === "suspended") {
      return res.status(403).json({
        error:  "Your account has been suspended. Contact a super admin.",
        status: "suspended",
      });
    }

    admin.last_login_at = new Date();
    admin.login_count   = (admin.login_count || 0) + 1;
    await admin.save();

    const token = jwt.sign(
      { adminId: admin._id, email: admin.email, name: admin.name, role: admin.role },
      JWT_SECRET,
      { expiresIn: "2h" },  // ✅ Reduced from 12h to 2h
    );

    // ✅ Set httpOnly cookie + return token for localStorage (hybrid)
    setAuthCookie(res, "admin_token", token, ADMIN_COOKIE_MAX_AGE);

    return res.json({
      ok:    true,
      token,
      admin: { name: admin.name, email: admin.email, role: admin.role, status: admin.status },
    });
  } catch (err) {
    console.error("Admin login error:", err);
    return res.status(500).json({ error: "Login failed" });
  }
});

// ═══════════════════════════════════════════════════════════
// PUBLIC: Logout — clears the admin cookie
// ═══════════════════════════════════════════════════════════
router.post("/logout", (req, res) => {
  const { clearAuthCookie } = require("../utils/setCookies");
  clearAuthCookie(res, "admin_token");
  return res.json({ ok: true });
});

// ═══════════════════════════════════════════════════════════
// PUBLIC: Download Excel template (no auth needed)
// ═══════════════════════════════════════════════════════════
router.get("/template", (req, res) => {
  const templatePath = path.join(__dirname, "..", "public", "Quiz_Upload_Template.xlsx");
  res.download(templatePath, "Quiz_Upload_Template.xlsx", (err) => {
    if (err) {
      console.error("Template download error:", err.message);
      res.status(404).json({ error: "Template file not found" });
    }
  });
});

// ═══════════════════════════════════════════════════════════
// ALL ROUTES BELOW REQUIRE ADMIN JWT
// ═══════════════════════════════════════════════════════════
router.use(requireAdmin);

// ───────────────────────────────────────────────────────────
// GET /api/admin/me
// ───────────────────────────────────────────────────────────
router.get("/me", async (req, res) => {
  try {
    const admin = await Admin.findById(req.admin.adminId)
      .select("email name role status last_login_at")
      .lean();
    if (!admin) return res.status(404).json({ error: "Admin not found" });
    return res.json({ ok: true, admin });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// ═══════════════════════════════════════════════════════════
// SUPER ADMIN ONLY — Invite System
// ═══════════════════════════════════════════════════════════

// ── POST /api/admin/invite ─────────────────────────────────
// Creates a one-time invite link. Only super_admin can call this.
router.post("/invite", requireSuperAdmin, async (req, res) => {
  try {
    await connectDB();

    const invite = await AdminInvite.create({
      created_by: req.admin.email,
    });

    const FRONTEND_URL = process.env.FRONTEND_ORIGIN || "http://localhost:5173";

    // ✅ Uses the secret admin path — not /admin/register
    const invite_url = `${FRONTEND_URL}/#/kai-ops-9281/register?invite=${invite.token}`;

    return res.json({
      ok:         true,
      invite_url,
      expires_in: "24 hours",
      created_by: req.admin.email,
    });
  } catch (err) {
    console.error("Create invite error:", err);
    return res.status(500).json({ error: err.message });
  }
});

// ── GET /api/admin/invites ─────────────────────────────────
// Lists all active (unused, non-expired) invites.
router.get("/invites", requireSuperAdmin, async (req, res) => {
  try {
    await connectDB();
    const invites = await AdminInvite.find({
      used:      false,
      expiresAt: { $gt: new Date() },
    })
      .sort({ createdAt: -1 })
      .select("token created_by createdAt expiresAt")
      .lean();

    const FRONTEND_URL = process.env.FRONTEND_ORIGIN || "http://localhost:5173";

    return res.json(
      invites.map((i) => ({
        ...i,
        invite_url: `${FRONTEND_URL}/#/kai-ops-9281/register?invite=${i.token}`,
      }))
    );
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// ── DELETE /api/admin/invites/:token ──────────────────────
// Revoke an invite before it is used.
router.delete("/invites/:token", requireSuperAdmin, async (req, res) => {
  try {
    await connectDB();
    await AdminInvite.deleteOne({ token: req.params.token });
    return res.json({ ok: true });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// ═══════════════════════════════════════════════════════════
// SUPER ADMIN ONLY — Admin Account Management
// ═══════════════════════════════════════════════════════════

router.get("/admins", requireSuperAdmin, async (req, res) => {
  try {
    await connectDB();
    const admins = await Admin.find()
      .select("email name role status last_login_at login_count approved_by approved_at createdAt")
      .sort({ createdAt: -1 })
      .lean();
    return res.json(admins);
  } catch (err) {
    console.error("List admins error:", err);
    return res.status(500).json({ error: err.message });
  }
});

router.patch("/admins/:adminId", requireSuperAdmin, async (req, res) => {
  try {
    await connectDB();
    const admin = await Admin.findById(req.params.adminId);
    if (!admin) return res.status(404).json({ error: "Admin not found" });

    if (admin._id.toString() === req.admin.adminId) {
      return res.status(400).json({ error: "You cannot modify your own account" });
    }

    const { action } = req.body;

    switch (action) {
      case "approve":
        if (admin.status !== "pending")
          return res.status(400).json({ error: "Admin is not pending" });
        admin.status      = "active";
        admin.approved_by = req.admin.email;
        admin.approved_at = new Date();
        break;
      case "suspend":
        if (admin.status === "suspended")
          return res.status(400).json({ error: "Already suspended" });
        admin.status = "suspended";
        break;
      case "reactivate":
        if (admin.status !== "suspended")
          return res.status(400).json({ error: "Admin is not suspended" });
        admin.status = "active";
        break;
      case "promote":
        if (admin.role === "super_admin")
          return res.status(400).json({ error: "Already a super admin" });
        if (admin.status !== "active")
          return res.status(400).json({ error: "Only active admins can be promoted" });
        admin.role = "super_admin";
        break;
      case "demote": {
        if (admin.role !== "super_admin")
          return res.status(400).json({ error: "Admin is not a super admin" });
        const superCount = await Admin.countDocuments({ role: "super_admin", status: "active" });
        if (superCount <= 1)
          return res.status(400).json({ error: "Cannot demote — at least one super admin must remain" });
        admin.role = "admin";
        break;
      }
      default:
        return res.status(400).json({ error: "Invalid action. Use: approve, suspend, reactivate, promote, demote" });
    }

    await admin.save();
    return res.json({
      ok:    true,
      admin: { _id: admin._id, email: admin.email, name: admin.name, role: admin.role, status: admin.status },
    });
  } catch (err) {
    console.error("Update admin error:", err);
    return res.status(500).json({ error: err.message });
  }
});

router.delete("/admins/:adminId", requireSuperAdmin, async (req, res) => {
  try {
    await connectDB();
    const admin = await Admin.findById(req.params.adminId);
    if (!admin) return res.status(404).json({ error: "Admin not found" });

    if (admin._id.toString() === req.admin.adminId) {
      return res.status(400).json({ error: "You cannot delete your own account" });
    }
    if (admin.role === "super_admin") {
      const superCount = await Admin.countDocuments({ role: "super_admin" });
      if (superCount <= 1)
        return res.status(400).json({ error: "Cannot delete the last super admin" });
    }

    await admin.deleteOne();
    return res.json({ ok: true, deleted: admin.email });
  } catch (err) {
    console.error("Delete admin error:", err);
    return res.status(500).json({ error: err.message });
  }
});

// ═══════════════════════════════════════════════════════════
// FILE UPLOAD
// ═══════════════════════════════════════════════════════════
const uploadDir = path.join(__dirname, "..", "public", "uploads");
if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir, { recursive: true });

const multerStorage = multer.diskStorage({
  destination: (req, file, cb) => {
    const sub = new Date().toISOString().slice(0, 7);
    const dir = path.join(uploadDir, sub);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    cb(null, dir);
  },
  filename: (req, file, cb) => {
    const ext  = path.extname(file.originalname).toLowerCase();
    const base = path.basename(file.originalname, ext).replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 50);
    cb(null, `${base}_${Date.now()}_${Math.random().toString(36).slice(2, 6)}${ext}`);
  },
});

const uploadMiddleware = multer({
  storage:    multerStorage,
  fileFilter: (req, file, cb) => {
    const ok = [
      "image/jpeg", "image/png", "image/gif", "image/webp", "image/svg+xml",
      "application/pdf",
      "audio/mpeg", "audio/wav", "audio/ogg", "audio/mp4", "audio/webm",
      "video/mp4", "video/webm", "video/ogg", "video/quicktime",
    ].includes(file.mimetype);
    cb(ok ? null : new Error("Allowed: images, PDFs, audio, and video"), ok);
  },
  limits: { fileSize: 50 * 1024 * 1024 },
});

router.post("/upload", (req, res) => {
  uploadMiddleware.single("file")(req, res, (err) => {
    if (err) {
      if (err.code === "LIMIT_FILE_SIZE")
        return res.status(400).json({ error: "File too large. Max 50MB." });
      return res.status(400).json({ error: err.message });
    }
    if (!req.file) return res.status(400).json({ error: "No file uploaded" });

    const relPath = req.file.path.replace(
      path.join(__dirname, "..", "public"),
      ""
    ).replace(/\\/g, "/");

    return res.json({
      ok:       true,
      url:      relPath,
      filename: req.file.filename,
      size:     req.file.size,
      mimetype: req.file.mimetype,
    });
  });
});

// ═══════════════════════════════════════════════════════════
// QUIZ ROUTES (unchanged from original)
// ═══════════════════════════════════════════════════════════

router.get("/quizzes", async (req, res) => {
  try {
    await connectDB();
    const quizzes = await Quiz.find()
      .sort({ year_level: 1, subject: 1, quiz_name: 1 })
      .select("-question_ids")
      .lean();
    return res.json(quizzes);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

router.patch("/quizzes/:quizId", async (req, res) => {
  try {
    await connectDB();
    const allowedFields = [
      "quiz_name", "year_level", "subject", "tier", "difficulty",
      "time_limit_minutes", "set_number", "is_active", "is_trial",
      "randomize_questions", "randomize_options", "voice_url", "video_url",
      "max_attempts", "passing_score",
    ];
    const updates = {};
    for (const f of allowedFields) {
      if (req.body[f] !== undefined) updates[f] = req.body[f];
    }
    if (Object.keys(updates).length === 0)
      return res.status(400).json({ error: "No valid fields to update" });

    const quiz = await Quiz.findOneAndUpdate(
      { quiz_id: req.params.quizId },
      { $set: updates },
      { new: true }
    ).lean();

    if (!quiz) return res.status(404).json({ error: "Quiz not found" });
    return res.json(quiz);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

router.delete("/quizzes/:quizId", async (req, res) => {
  try {
    await connectDB();
    const quiz = await Quiz.findOneAndDelete({ quiz_id: req.params.quizId });
    if (!quiz) return res.status(404).json({ error: "Quiz not found" });
    await Question.deleteMany({ quiz_ids: req.params.quizId });
    return res.json({ ok: true, deleted: req.params.quizId });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// ═══════════════════════════════════════════════════════════
// BUNDLE ROUTES (unchanged from original)
// ═══════════════════════════════════════════════════════════

router.get("/bundles", async (req, res) => {
  try {
    await connectDB();
    const bundles = await QuizCatalog.find()
      .sort({ year_level: 1, tier: 1 })
      .lean();
    return res.json(
      bundles.map((b) => ({
        ...b,
        quiz_ids: b.quiz_ids || b.flexiquiz_quiz_ids || [],
        currency: b.currency || "aud",
      }))
    );
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

router.get("/bundles/:bundleId", async (req, res) => {
  try {
    await connectDB();
    const bundle = await QuizCatalog.findOne({ bundle_id: req.params.bundleId }).lean();
    if (!bundle) return res.status(404).json({ error: "Bundle not found" });
    return res.json({
      ...bundle,
      quiz_ids: bundle.quiz_ids || bundle.flexiquiz_quiz_ids || [],
      currency: bundle.currency || "aud",
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

router.post("/bundles", async (req, res) => {
  try {
    await connectDB();
    const {
      bundle_name, description, year_level, tier,
      price_cents, currency, max_quiz_count, questions_per_quiz,
      distribution_mode, swap_eligible_from, subjects,
    } = req.body;

    if (!bundle_name?.trim())
      return res.status(400).json({ error: "bundle_name is required" });
    if (price_cents === undefined || Number(price_cents) < 0)
      return res.status(400).json({ error: "price_cents is required and must be >= 0" });

    const yearSlug  = year_level ? String(year_level).trim().toLowerCase().replace(/[^a-z0-9]+/g, "_") : "general";
    const tierSlug  = tier       ? `_${String(tier).trim().toLowerCase().replace(/[^a-z0-9]+/g, "_")}` : "";
    const nameSlug  = bundle_name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "_");
    const bundle_id = `${yearSlug}${tierSlug}_${nameSlug}_${Date.now().toString(36)}`;

    const bundle = await QuizCatalog.create({
      bundle_id,
      bundle_name:       bundle_name.trim(),
      description:       (description || "").trim(),
      year_level:        year_level ? String(year_level).trim() : null,
      tier:              tier ? String(tier).trim() : null,
      price_cents:       Number(price_cents),
      currency:          currency || "aud",
      max_quiz_count:    max_quiz_count ? Number(max_quiz_count) : undefined,
      questions_per_quiz: questions_per_quiz ? Number(questions_per_quiz) : undefined,
      distribution_mode: distribution_mode || "standard",
      swap_eligible_from: distribution_mode === "swap" ? (swap_eligible_from || []) : [],
      subjects:          Array.isArray(subjects) ? subjects : [],
      is_active:         true,
      quiz_ids:          [],
      quiz_count:        0,
    });

    return res.status(201).json({ ok: true, bundle });
  } catch (err) {
    console.error("Create bundle error:", err);
    return res.status(500).json({ error: err.message });
  }
});

router.patch("/bundles/:bundleId", async (req, res) => {
  try {
    await connectDB();
    const bundle = await QuizCatalog.findOne({ bundle_id: req.params.bundleId });
    if (!bundle) return res.status(404).json({ error: "Bundle not found" });

    const allowed = [
      "bundle_name", "description", "year_level", "tier", "price_cents",
      "currency", "is_active", "max_quiz_count", "questions_per_quiz",
      "distribution_mode", "swap_eligible_from", "subjects",
    ];
    for (const f of allowed) {
      if (req.body[f] !== undefined) bundle[f] = req.body[f];
    }
    await bundle.save();
    return res.json({ ok: true, bundle });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

router.delete("/bundles/:bundleId", async (req, res) => {
  try {
    await connectDB();
    const bundle = await QuizCatalog.findOneAndDelete({ bundle_id: req.params.bundleId });
    if (!bundle) return res.status(404).json({ error: "Bundle not found" });
    return res.json({ ok: true, deleted: req.params.bundleId });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

router.post("/bundles/:bundleId/quizzes", async (req, res) => {
  try {
    await connectDB();
    const { quiz_id } = req.body;
    if (!quiz_id) return res.status(400).json({ error: "quiz_id is required" });

    const bundle = await QuizCatalog.findOne({ bundle_id: req.params.bundleId });
    if (!bundle) return res.status(404).json({ error: "Bundle not found" });

    const quiz = await Quiz.findOne({ quiz_id });
    if (!quiz) return res.status(404).json({ error: "Quiz not found" });

    if (!bundle.quiz_ids) bundle.quiz_ids = [...(bundle.flexiquiz_quiz_ids || [])];
    if (!bundle.quiz_ids.includes(quiz_id)) bundle.quiz_ids.push(quiz_id);
    if (!bundle.flexiquiz_quiz_ids) bundle.flexiquiz_quiz_ids = [];
    if (!bundle.flexiquiz_quiz_ids.includes(quiz_id)) bundle.flexiquiz_quiz_ids.push(quiz_id);

    bundle.quiz_count = bundle.quiz_ids.length;
    await bundle.save();

    const syncResult = await Child.updateMany(
      { entitled_bundle_ids: bundle.bundle_id },
      { $addToSet: { entitled_quiz_ids: quiz_id } }
    );

    // Auto-reprovision failed purchases
    const failedPurchases = await Purchase.find({
      bundle_id: bundle.bundle_id,
      status:    "paid",
      provisioned: false,
    });
    let reprovisioned = 0;
    for (const purchase of failedPurchases) {
      for (const childId of (purchase.child_ids || [])) {
        await Child.findByIdAndUpdate(childId, {
          $set:      { status: "active" },
          $addToSet: { entitled_bundle_ids: bundle.bundle_id, entitled_quiz_ids: { $each: bundle.quiz_ids } },
        });
      }
      await Purchase.findByIdAndUpdate(purchase._id, {
        $set: { provisioned: true, provisioned_at: new Date(), provision_error: null },
      });
      reprovisioned++;
    }

    return res.json({
      ok:                    true,
      quiz_count:            bundle.quiz_count,
      children_synced:       syncResult.modifiedCount,
      purchases_reprovisioned: reprovisioned,
    });
  } catch (err) {
    console.error("Add quiz to bundle error:", err);
    return res.status(500).json({ error: err.message });
  }
});

router.delete("/bundles/:bundleId/quizzes", async (req, res) => {
  try {
    await connectDB();
    const { quiz_id } = req.body;
    if (!quiz_id) return res.status(400).json({ error: "quiz_id is required" });

    const bundle = await QuizCatalog.findOne({ bundle_id: req.params.bundleId });
    if (!bundle) return res.status(404).json({ error: "Bundle not found" });

    bundle.quiz_ids           = (bundle.quiz_ids           || []).filter((q) => q !== quiz_id);
    bundle.flexiquiz_quiz_ids = (bundle.flexiquiz_quiz_ids || []).filter((q) => q !== quiz_id);
    bundle.quiz_count         = bundle.quiz_ids.length;
    await bundle.save();

    return res.json({ ok: true, quiz_count: bundle.quiz_count });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

module.exports = router;
