/**
 * routes/adminRoutes.js
 *
 * Single-role admin system — all admins have equal access.
 * No super_admin tier. Invite system remains so new admins
 * can only join via a one-time link generated by an existing admin.
 *
 * Registration: invite token required → account auto-approved (active).
 * Any logged-in admin can manage other admins (approve, suspend, delete).
 */

const { setAuthCookie }    = require("../utils/setCookies");
const ADMIN_COOKIE_MAX_AGE = 2 * 60 * 60 * 1000; // 2 hours

const express    = require("express");
const path       = require("path");
const fs         = require("fs");
const jwt        = require("jsonwebtoken");
const bcrypt     = require("bcrypt");
const { v4: uuidv4 } = require("uuid");
const multer     = require("multer");
const rateLimit  = require("express-rate-limit");

const { requireAdmin }  = require("../middleware/adminAuth");
const Admin             = require("../models/admin");
const AdminInvite       = require("../models/adminInvite");
const Quiz              = require("../models/quiz");
const Question          = require("../models/question");
const QuizCatalog       = require("../models/quizCatalog");
const Child             = require("../models/child");
const Purchase          = require("../models/purchase");
const connectDB         = require("../config/db");

const router     = express.Router();
const JWT_SECRET = process.env.JWT_SECRET || process.env.PARENT_JWT_SECRET;

// ═══════════════════════════════════════════════════════════
// Strict rate limiter for login — 5 attempts / 15 min per IP
// ═══════════════════════════════════════════════════════════
const adminLoginLimiter = rateLimit({
  windowMs:        15 * 60 * 1000,
  max:             5,
  message:         { error: "Too many login attempts. Try again in 15 minutes." },
  standardHeaders: true,
  legacyHeaders:   false,
});

// ═══════════════════════════════════════════════════════════
// PUBLIC: Seed / first-run check
// ═══════════════════════════════════════════════════════════
router.get("/check", async (req, res) => {
  try {
    await connectDB();
    const count = await Admin.countDocuments();
    return res.json({ has_admin: count > 0 });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// ═══════════════════════════════════════════════════════════
// PUBLIC: Admin Register — requires a valid invite token
//
// Flow:
//   1. Any admin calls POST /api/admin/invite
//   2. Backend creates AdminInvite record, returns invite URL
//   3. Admin sends URL to colleague
//   4. Colleague opens URL → AdminRegister.jsx reads ?invite= from URL
//   5. Colleague submits form → account created as active immediately
// ═══════════════════════════════════════════════════════════
router.post("/register", async (req, res) => {
  try {
    await connectDB();

    const invite_token = String(req.body?.invite_token || "").trim();
    const name         = String(req.body?.name         || "").trim();
    const email        = String(req.body?.email        || "").trim().toLowerCase();
    const password     = String(req.body?.password     || "");

    // ── Validate invite token ──────────────────────────────
    if (!invite_token) {
      return res.status(403).json({
        error: "A valid invite link is required to register. Ask an admin for an invite.",
      });
    }

    const invite = await AdminInvite.findOne({
      token:    invite_token,
      used:     false,
      expiresAt: { $gt: new Date() },
    });

    if (!invite) {
      return res.status(403).json({
        error: "This invite link is invalid or has expired. Ask an admin for a new one.",
      });
    }

    // ── Validate inputs ────────────────────────────────────
    if (!name)  return res.status(400).json({ error: "Name is required" });
    if (!email) return res.status(400).json({ error: "Email is required" });

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return res.status(400).json({ error: "Valid email is required" });
    }
    if (!password || password.length < 12) {
      return res.status(400).json({ error: "Password must be at least 12 characters" });
    }
    if (!/[A-Z]/.test(password)) {
      return res.status(400).json({ error: "Password must contain at least one uppercase letter" });
    }
    if (!/[0-9]/.test(password)) {
      return res.status(400).json({ error: "Password must contain at least one number" });
    }

    const existing = await Admin.findOne({ email });
    if (existing) {
      return res.status(409).json({ error: "An account with this email already exists" });
    }

    // ── Mark invite as used BEFORE creating admin ──────────
    invite.used = true;
    await invite.save();

    // ── Hash password explicitly ───────────────────────────
    const password_hash = await bcrypt.hash(password, 12);

    const admin = await Admin.create({
      email,
      name,
      password_hash,
      role:   "admin",
      status: "active", // auto-approved — no super_admin needed
    });

    return res.status(201).json({
      ok:      true,
      message: "Account created. You can now log in.",
      admin:   { name: admin.name, email: admin.email, role: admin.role, status: admin.status },
    });
  } catch (err) {
    console.error("Admin register error:", err);
    return res.status(500).json({ error: "Registration failed" });
  }
});

// ═══════════════════════════════════════════════════════════
// PUBLIC: Admin Login
// ═══════════════════════════════════════════════════════════
router.post("/login", adminLoginLimiter, async (req, res) => {
  try {
    await connectDB();

    const email    = String(req.body?.email    || "").trim().toLowerCase();
    const password = String(req.body?.password || "");

    if (!email || !password) {
      return res.status(400).json({ error: "Email and password are required" });
    }

    const admin = await Admin.findOne({ email });
    if (!admin) {
      return res.status(401).json({ error: "Invalid email or password" });
    }

    const isValid = await admin.comparePassword(password);
    if (!isValid) {
      return res.status(401).json({ error: "Invalid email or password" });
    }

    if (admin.status === "pending") {
      return res.status(403).json({
        error:  "Your account is pending approval.",
        status: "pending",
      });
    }
    if (admin.status === "suspended") {
      return res.status(403).json({
        error:  "Your account has been suspended. Contact another admin.",
        status: "suspended",
      });
    }

    admin.last_login_at = new Date();
    admin.login_count   = (admin.login_count || 0) + 1;
    await admin.save();

    const token = jwt.sign(
      { adminId: admin._id, email: admin.email, name: admin.name, role: admin.role },
      JWT_SECRET,
      { expiresIn: "2h" },
    );

    setAuthCookie(res, "admin_token", token, ADMIN_COOKIE_MAX_AGE);

    return res.json({
      ok:    true,
      token,
      admin: { name: admin.name, email: admin.email, role: admin.role, status: admin.status },
    });
  } catch (err) {
    console.error("Admin login error:", err);
    return res.status(500).json({ error: "Login failed" });
  }
});

// ═══════════════════════════════════════════════════════════
// PUBLIC: Logout — clears the admin cookie
// ═══════════════════════════════════════════════════════════
router.post("/logout", (req, res) => {
  const { clearAuthCookie } = require("../utils/setCookies");
  clearAuthCookie(res, "admin_token");
  return res.json({ ok: true });
});

// ═══════════════════════════════════════════════════════════
// PUBLIC: Download Excel template (no auth needed)
// ═══════════════════════════════════════════════════════════
router.get("/template", (req, res) => {
  const templatePath = path.join(__dirname, "..", "public", "Quiz_Upload_Template.xlsx");
  res.download(templatePath, "Quiz_Upload_Template.xlsx", (err) => {
    if (err) {
      console.error("Template download error:", err.message);
      res.status(404).json({ error: "Template file not found" });
    }
  });
});

// ═══════════════════════════════════════════════════════════
// ALL ROUTES BELOW REQUIRE ADMIN JWT
// ═══════════════════════════════════════════════════════════
router.use(requireAdmin);

// ───────────────────────────────────────────────────────────
// GET /api/admin/me
// ───────────────────────────────────────────────────────────
router.get("/me", async (req, res) => {
  try {
    const admin = await Admin.findById(req.admin.adminId)
      .select("email name role status last_login_at")
      .lean();
    if (!admin) return res.status(404).json({ error: "Admin not found" });
    return res.json({ ok: true, admin });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// ═══════════════════════════════════════════════════════════
// INVITE SYSTEM — any admin can invite a new admin
// ═══════════════════════════════════════════════════════════

// POST /api/admin/invite — generate a one-time invite link
router.post("/invite", async (req, res) => {
  try {
    await connectDB();

    const invite = await AdminInvite.create({
      created_by: req.admin.email,
    });

    const FRONTEND_URL = process.env.FRONTEND_ORIGIN || "http://localhost:5173";
    const invite_url = `${FRONTEND_URL}/#/kai-ops-9281/register?invite=${invite.token}`;

    return res.json({
      ok:         true,
      invite_url,
      expires_in: "24 hours",
      created_by: req.admin.email,
    });
  } catch (err) {
    console.error("Create invite error:", err);
    return res.status(500).json({ error: err.message });
  }
});

// GET /api/admin/invites — list active invites
router.get("/invites", async (req, res) => {
  try {
    await connectDB();
    const invites = await AdminInvite.find({
      used:      false,
      expiresAt: { $gt: new Date() },
    })
      .sort({ createdAt: -1 })
      .select("token created_by createdAt expiresAt")
      .lean();

    const FRONTEND_URL = process.env.FRONTEND_ORIGIN || "http://localhost:5173";

    return res.json(
      invites.map((i) => ({
        ...i,
        invite_url: `${FRONTEND_URL}/#/kai-ops-9281/register?invite=${i.token}`,
      }))
    );
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// DELETE /api/admin/invites/:token — revoke an invite
router.delete("/invites/:token", async (req, res) => {
  try {
    await connectDB();
    await AdminInvite.deleteOne({ token: req.params.token });
    return res.json({ ok: true });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// ═══════════════════════════════════════════════════════════
// ADMIN ACCOUNT MANAGEMENT — any admin can manage others
// ═══════════════════════════════════════════════════════════

router.get("/admins", async (req, res) => {
  try {
    await connectDB();
    const admins = await Admin.find()
      .select("email name role status last_login_at login_count approved_by approved_at createdAt")
      .sort({ createdAt: -1 })
      .lean();
    return res.json(admins);
  } catch (err) {
    console.error("List admins error:", err);
    return res.status(500).json({ error: err.message });
  }
});

router.get("/admins/pending", async (req, res) => {
  try {
    await connectDB();
    const admins = await Admin.find({ status: "pending" })
      .select("email name role status createdAt")
      .sort({ createdAt: -1 })
      .lean();
    return res.json(admins);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

router.patch("/admins/:adminId", async (req, res) => {
  try {
    await connectDB();
    const admin = await Admin.findById(req.params.adminId);
    if (!admin) return res.status(404).json({ error: "Admin not found" });

    if (admin._id.toString() === req.admin.adminId) {
      return res.status(400).json({ error: "You cannot modify your own account" });
    }

    const { action } = req.body;

    switch (action) {
      case "approve":
        if (admin.status !== "pending")
          return res.status(400).json({ error: "Admin is not pending" });
        admin.status      = "active";
        admin.approved_by = req.admin.email;
        admin.approved_at = new Date();
        break;
      case "suspend":
        if (admin.status === "suspended")
          return res.status(400).json({ error: "Already suspended" });
        admin.status = "suspended";
        break;
      case "reactivate":
        if (admin.status !== "suspended")
          return res.status(400).json({ error: "Admin is not suspended" });
        admin.status = "active";
        break;
      default:
        return res.status(400).json({ error: "Invalid action. Use: approve, suspend, reactivate" });
    }

    await admin.save();
    return res.json({
      ok:    true,
      admin: { _id: admin._id, email: admin.email, name: admin.name, role: admin.role, status: admin.status },
    });
  } catch (err) {
    console.error("Update admin error:", err);
    return res.status(500).json({ error: err.message });
  }
});

router.delete("/admins/:adminId", async (req, res) => {
  try {
    await connectDB();
    const admin = await Admin.findById(req.params.adminId);
    if (!admin) return res.status(404).json({ error: "Admin not found" });

    if (admin._id.toString() === req.admin.adminId) {
      return res.status(400).json({ error: "You cannot delete your own account" });
    }

    // Prevent deleting the last active admin
    const activeCount = await Admin.countDocuments({ status: "active" });
    if (activeCount <= 1 && admin.status === "active") {
      return res.status(400).json({ error: "Cannot delete the last active admin account" });
    }

    await admin.deleteOne();
    return res.json({ ok: true, deleted: admin.email });
  } catch (err) {
    console.error("Delete admin error:", err);
    return res.status(500).json({ error: err.message });
  }
});

// ═══════════════════════════════════════════════════════════
// FILE UPLOAD
// ═══════════════════════════════════════════════════════════
const uploadDir = path.join(__dirname, "..", "public", "uploads");
if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir, { recursive: true });

const multerStorage = multer.diskStorage({
  destination: (req, file, cb) => {
    const sub = new Date().toISOString().slice(0, 7);
    const dir = path.join(uploadDir, sub);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    cb(null, dir);
  },
  filename: (req, file, cb) => {
    const ext  = path.extname(file.originalname).toLowerCase();
    const base = path.basename(file.originalname, ext).replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 50);
    cb(null, `${base}_${Date.now()}_${Math.random().toString(36).slice(2, 6)}${ext}`);
  },
});

const uploadMiddleware = multer({
  storage:    multerStorage,
  fileFilter: (req, file, cb) => {
    const ok = [
      "image/jpeg", "image/png", "image/gif", "image/webp", "image/svg+xml",
      "application/pdf",
      "audio/mpeg", "audio/wav", "audio/ogg", "audio/mp4", "audio/webm",
      "video/mp4", "video/webm", "video/ogg", "video/quicktime",
    ].includes(file.mimetype);
    cb(ok ? null : new Error("Allowed: images, PDFs, audio, and video"), ok);
  },
  limits: { fileSize: 50 * 1024 * 1024 },
});

router.post("/upload", (req, res) => {
  uploadMiddleware.single("file")(req, res, (err) => {
    if (err) {
      if (err.code === "LIMIT_FILE_SIZE")
        return res.status(400).json({ error: "File too large. Max 50MB." });
      return res.status(400).json({ error: err.message });
    }
    if (!req.file) return res.status(400).json({ error: "No file uploaded" });

    const relPath = req.file.path.replace(
      path.join(__dirname, "..", "public"),
      ""
    ).replace(/\\/g, "/");

    return res.json({
      ok:       true,
      url:      relPath,
      filename: req.file.filename,
      size:     req.file.size,
      mimetype: req.file.mimetype,
    });
  });
});

// ═══════════════════════════════════════════════════════════
// QUIZ ROUTES
// ═══════════════════════════════════════════════════════════

router.get("/quizzes", async (req, res) => {
  try {
    await connectDB();
    const quizzes = await Quiz.find()
      .sort({ year_level: 1, subject: 1, quiz_name: 1 })
      .select("-question_ids")
      .lean();
    return res.json(quizzes);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

router.patch("/quizzes/:quizId", async (req, res) => {
  try {
    await connectDB();
    const allowedFields = [
      "quiz_name", "year_level", "subject", "tier", "difficulty",
      "time_limit_minutes", "set_number", "is_active", "is_trial",
      "randomize_questions", "randomize_options", "voice_url", "video_url",
      "max_attempts", "passing_score",
    ];
    const updates = {};
    for (const f of allowedFields) {
      if (req.body[f] !== undefined) updates[f] = req.body[f];
    }
    if (Object.keys(updates).length === 0)
      return res.status(400).json({ error: "No valid fields to update" });

    const quiz = await Quiz.findOneAndUpdate(
      { quiz_id: req.params.quizId },
      { $set: updates },
      { new: true }
    ).lean();

    if (!quiz) return res.status(404).json({ error: "Quiz not found" });
    return res.json(quiz);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

router.delete("/quizzes/:quizId", async (req, res) => {
  try {
    await connectDB();
    const quiz = await Quiz.findOneAndDelete({ quiz_id: req.params.quizId });
    if (!quiz) return res.status(404).json({ error: "Quiz not found" });
    await Question.deleteMany({ quiz_ids: req.params.quizId });
    return res.json({ ok: true, deleted: req.params.quizId });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// ═══════════════════════════════════════════════════════════
// QUIZ UPLOAD
// ═══════════════════════════════════════════════════════════

router.post("/quizzes/upload", async (req, res) => {
  try {
    await connectDB();
    const { quiz: quizData, questions: questionsData } = req.body;

    if (!quizData?.quiz_name?.trim()) {
      return res.status(400).json({ error: "quiz_name is required" });
    }
    if (!Array.isArray(questionsData) || questionsData.length === 0) {
      return res.status(400).json({ error: "At least one question is required" });
    }

    const quiz_id = uuidv4();

    const questions = await Question.insertMany(
      questionsData.map((q) => ({
        question_id:   uuidv4(),
        quiz_ids:      [quiz_id],
        text:          q.question_text || q.text || "",  // ✅ correct field name
        type:          q.type || "radio_button",          // ✅ valid enum value
        options:       q.options || [],
        correct_answer: q.correct_answer || null,
        points:        q.points || 1,
        // ✅ categories is [{name}] array, not a plain string
        categories:    q.category
          ? [{ name: q.category }]
          : (q.categories || []),
        image_url:     q.image_url  || null,
        explanation:   q.explanation || "",
        voice_url:     q.voice_url  || null,
        video_url:     q.video_url  || null,
        image_width:   q.image_width  || null,
        image_height:  q.image_height || null,
      }))
    );

    const quiz = await Quiz.create({
      quiz_id,
      quiz_name:          quizData.quiz_name.trim(),
      year_level:         quizData.year_level || null,
      subject:            quizData.subject || null,
      tier:               quizData.tier || "A",
      time_limit_minutes: quizData.time_limit_minutes || null,
      difficulty:         quizData.difficulty || null,
      set_number:         quizData.set_number || 1,
      is_trial:           quizData.is_trial || false,
      is_active:          true,
      voice_url:          quizData.voice_url || null,
      video_url:          quizData.video_url || null,
      question_ids:       questions.map((q) => q.question_id),
      question_count:     questions.length,
    });

    return res.status(201).json({
      ok:             true,
      quiz_id:        quiz.quiz_id,
      quiz_name:      quiz.quiz_name,
      question_count: questions.length,
    });
  } catch (err) {
    console.error("Quiz upload error:", err);
    return res.status(500).json({ error: err.message });
  }
});

// ═══════════════════════════════════════════════════════════
// BUNDLE ROUTES
// ═══════════════════════════════════════════════════════════

router.get("/bundles", async (req, res) => {
  try {
    await connectDB();
    const bundles = await QuizCatalog.find()
      .sort({ year_level: 1, tier: 1 })
      .lean();
    return res.json(
      bundles.map((b) => ({
        ...b,
        quiz_ids: b.quiz_ids || b.flexiquiz_quiz_ids || [],
        currency: b.currency || "aud",
      }))
    );
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

router.get("/bundles/:bundleId", async (req, res) => {
  try {
    await connectDB();
    const bundle = await QuizCatalog.findOne({ bundle_id: req.params.bundleId }).lean();
    if (!bundle) return res.status(404).json({ error: "Bundle not found" });
    return res.json({
      ...bundle,
      quiz_ids: bundle.quiz_ids || bundle.flexiquiz_quiz_ids || [],
      currency: bundle.currency || "aud",
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

router.post("/bundles", async (req, res) => {
  try {
    await connectDB();
    const {
      bundle_name, description, year_level, tier,
      price_cents, currency, max_quiz_count, questions_per_quiz,
      distribution_mode, swap_eligible_from, subjects,
    } = req.body;

    if (!bundle_name?.trim())
      return res.status(400).json({ error: "bundle_name is required" });
    if (price_cents === undefined || Number(price_cents) < 0)
      return res.status(400).json({ error: "price_cents is required and must be >= 0" });

    const yearSlug  = year_level ? String(year_level).trim().toLowerCase().replace(/[^a-z0-9]+/g, "_") : "general";
    const tierSlug  = tier       ? String(tier).trim().toLowerCase().replace(/[^a-z0-9]+/g, "_")       : "standard";
    const nameSlug  = bundle_name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "_").slice(0, 30);
    const bundle_id = `bundle_${yearSlug}_${tierSlug}_${nameSlug}_${Date.now()}`;

    const bundle = await QuizCatalog.create({
      bundle_id,
      bundle_name:        bundle_name.trim(),
      description:        description || "",
      year_level:         year_level  || null,
      tier:               tier        || "A",
      price_cents:        Number(price_cents),
      currency:           currency    || "aud",
      max_quiz_count:     max_quiz_count     || null,
      questions_per_quiz: questions_per_quiz || null,
      distribution_mode:  distribution_mode  || "fixed",
      swap_eligible_from: swap_eligible_from || null,
      subjects:           subjects    || [],
      quiz_ids:           [],
      is_active:          true,
    });

    return res.status(201).json(bundle);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

router.patch("/bundles/:bundleId", async (req, res) => {
  try {
    await connectDB();
    const allowedFields = [
      "bundle_name", "description", "year_level", "tier", "price_cents",
      "currency", "is_active", "max_quiz_count", "questions_per_quiz",
      "distribution_mode", "swap_eligible_from", "subjects",
    ];
    const updates = {};
    for (const f of allowedFields) {
      if (req.body[f] !== undefined) updates[f] = req.body[f];
    }

    const bundle = await QuizCatalog.findOneAndUpdate(
      { bundle_id: req.params.bundleId },
      { $set: updates },
      { new: true }
    ).lean();

    if (!bundle) return res.status(404).json({ error: "Bundle not found" });
    return res.json(bundle);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

router.delete("/bundles/:bundleId", async (req, res) => {
  try {
    await connectDB();
    const bundle = await QuizCatalog.findOneAndDelete({ bundle_id: req.params.bundleId });
    if (!bundle) return res.status(404).json({ error: "Bundle not found" });
    return res.json({ ok: true, deleted: req.params.bundleId });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// PATCH /bundles/:bundleId/quizzes — set the quiz_ids list for a bundle
router.patch("/bundles/:bundleId/quizzes", async (req, res) => {
  try {
    await connectDB();
    const { quiz_ids } = req.body;
    if (!Array.isArray(quiz_ids))
      return res.status(400).json({ error: "quiz_ids must be an array" });

    const bundle = await QuizCatalog.findOneAndUpdate(
      { bundle_id: req.params.bundleId },
      { $set: { quiz_ids, quiz_count: quiz_ids.length } },
      { new: true }
    ).lean();

    if (!bundle) return res.status(404).json({ error: "Bundle not found" });
    return res.json(bundle);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// ═══════════════════════════════════════════════════════════
// CHILDREN / PURCHASE MANAGEMENT
// ═══════════════════════════════════════════════════════════

router.get("/children", async (req, res) => {
  try {
    await connectDB();
    const children = await Child.find()
      .select("name username year_level entitled_bundle_ids parent_id createdAt")
      .sort({ createdAt: -1 })
      .lean();
    return res.json(children);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

router.patch("/children/:childId/bundles", async (req, res) => {
  try {
    await connectDB();
    const { bundle_ids } = req.body;
    if (!Array.isArray(bundle_ids))
      return res.status(400).json({ error: "bundle_ids must be an array" });

    const child = await Child.findByIdAndUpdate(
      req.params.childId,
      { $set: { entitled_bundle_ids: bundle_ids } },
      { new: true }
    ).lean();

    if (!child) return res.status(404).json({ error: "Child not found" });
    return res.json({ ok: true, child });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

module.exports = router;