// src/app/components/auth/AIGradingConsent.jsx
//
// Modal body for the "AI Marking Policy" link on the parent signup form.
//
// ⚠️ DUPLICATE: an identical AIGradingPolicy() function is defined locally
//    inside pages/ParentCreatePage.jsx (an earlier import of this module
//    failed to resolve and broke the Vite build). THAT copy is the one the
//    signup modal actually renders. Any wording change must be made in BOTH
//    files or the live site will not change.

export default function AIGradingPolicy() {
  return (
    <div className="space-y-4 text-sm leading-relaxed text-gray-700">
      <p>
        Some of your child&apos;s practice work is marked automatically by
        artificial intelligence rather than by a teacher. This applies to writing
        tasks and to any photo of handwriting that is uploaded.
      </p>

      <ul className="list-disc space-y-2 pl-5">
        <li>
          Scores and feedback are generated by a third-party artificial
          intelligence service. A human does not review every piece of work
          before you see the result.
        </li>
        <li>
          That service operates overseas, so your child&apos;s work may be
          processed on servers outside Australia.
        </li>
        <li>
          AI marking is not perfect and can misread handwriting. Treat results as
          practice guidance, not as an official NAPLAN assessment.
        </li>
        <li>
          You can delete your child&apos;s profile and all stored work at any time
          from the parent dashboard.
        </li>
      </ul>

      <p>
        Full details, including the identity of our AI provider, are set out in
        our Privacy Policy.
      </p>
    </div>
  );
}